---

- name: AÃ±adir repositorio postgresql
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: true


- name: Instalar postgresql
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - postgresql15-server
    - python39
    - python3-psycopg2


- name: Inicializar postgresql
  ansible.builtin.command:
    cmd: postgresql-15-setup initdb
  register: ini_postgres
  failed_when: ini_postgres.changed == "false"
  changed_when: false


- name: Iniciar servicio postgresql
  ansible.builtin.service:
    state: started
    name: postgresql-15
    enabled: true

...
